version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    network_mode: host

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./api:/api
    network_mode: host

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./app:/app
    depends_on:
      - api
    network_mode: host

volumes:
  mongodb_data:
    driver: local
